language: cpp

env:
  global:
    - OMP_NUM_THREADS=4

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libblas-dev
            - liblapack-dev
            - python-dev
#            - swig3.0
      env:
        - PYTHON_CFLAGS="-I/usr/include/python2.7"
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libatlas-base-dev
            - liblapack-dev
            - python-dev
#            - swig3.0
      env:
        - PYTHON_CFLAGS="-I/usr/include/python2.7"
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libopenblas-dev
            - liblapack-dev
            - python-dev
#            - swig3.0
      env:
        - PYTHON_CFLAGS="-I/usr/include/python2.7"
    - os: linux
      dist: xenial  # To ensure clang 7 for __builtin_cpu_init().
      compiler: clang
      addons:
        apt:
          packages:
            - libopenblas-dev
            - liblapack-dev
            - python-dev
#            - swig3.0
      env:
        - PYTHON_CFLAGS="-I/usr/include/python2.7"
        # NOTE: Hack, c.f. https://github.com/travis-ci/travis-ci/issues/8613
        - LD_LIBRARY_PATH="/usr/local/clang/lib"
    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - swig
          update: true
      env:
        - MATRIX_EVAL="which gcc; export CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++"
    - os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            - llvm
            - swig
          update: true
      env:
        - MATRIX_EVAL="brew link --overwrite llvm; export CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++"
        - LDFLAGS="-L/usr/local/opt/llvm/lib"
        - CPPFLAGS="-I/usr/local/opt/llvm/include"
  allow_failures:
    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - swig
          update: true
      env:
        - MATRIX_EVAL="which gcc; export CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++"

before_install:
  - eval "$MATRIX_EVAL"
  - pip install --user scipy

install:
  - ./.travis/install.sh
  - aclocal
  - autoconf
  - ./configure --without-cuda
  - make
  - make -C python

script:
  - make test
